on:
  push:
    branches: [ master ]
  pull_request:
name: CI
jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: easyeffects.flatpak
        manifest-path: util/flatpak/com.github.wwmm.easyeffects.json
        cache-key: flatpak-builder-${{ github.sha }}   
  arch:
    name: Arch
    runs-on: ubuntu-20.04
    container:
      image: archlinux
    
    steps:
    - name: prepare
      run: |
        useradd build
        echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        su build
    - uses: actions/checkout@v3.0.2
    - name: build
      run: |
        makepkg -si

      
      
