on:
  push:
    branches: [ master ]
  pull_request:
name: CI
jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Get hash
      run: | 
        git config --global --add safe.directory /__w/easyeffects/easyeffects
        echo "GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: easyeffects-flatpak-${{ env.GIT_HASH }}.flatpak
        manifest-path: util/flatpak/com.github.wwmm.easyeffects.json
        cache-key: flatpak-builder-${{ github.sha }}   
  arch:
    name: Arch
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0
    - name: Get Hash
      run: echo "GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
    - name: Makepkg Build and Check
      id: makepkg
      uses: vchernin/pkgbuild-action@master
    - name: Upload Package Archive
      uses: actions/upload-artifact@v3.1.0
      with:
        name: easyeffects-archlinux-${{ env.GIT_HASH }}-x86-64
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
        if-no-files-found: error
