on:
  push:
    branches: [ master ]
  pull_request:
name: CI
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-20.04
    outputs:
      github_commit_desc: ${{ steps.get_commit_desc.outputs.github_commit_desc }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Get head branch latest commit
        run: echo "GITHUB_PR_HEAD_SHA=$(git log --pretty=format:'%h' $GITHUB_SHA^2 -1)" >> $GITHUB_ENV

      - name: Get base branch latest commit
        run: echo "GITHUB_PR_BASE_SHA=$(git log --pretty=format:'%h' $GITHUB_SHA^1 -1)" >> $GITHUB_ENV

      - name: Get latest commit
        run: echo "GITHUB_HEAD_SHA=$(git log --pretty=format:'%h' -1)" >> $GITHUB_ENV
      
      - id: get_commit_desc
        run: | 
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "::set-output name=github_commit_desc::merge-${{ env.GITHUB_PR_HEAD_SHA }}-into-${{ env.GITHUB_PR_BASE_SHA }}"
          else
            echo "::set-output name=github_commit_desc::master-${{ env.GITHUB_HEAD_SHA }}"
          fi

  flatpak:
    name: Flatpak
    runs-on: ubuntu-20.04
    needs: prepare
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2

    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: easyeffects-flatpak-${{ needs.prepare.outputs.github_commit_desc }}.flatpak
        manifest-path: util/flatpak/com.github.wwmm.easyeffects.json
        cache-key: flatpak-builder-${{ github.sha }}

  arch:
    name: Arch
    runs-on: ubuntu-20.04
    needs: prepare
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Save commit description to file
      run: echo ${{ needs.prepare.outputs.github_commit_desc }} >> GITHUB_COMMIT_DESC

    - name: Makepkg Build and Check
      id: makepkg
      uses: vchernin/pkgbuild-action@master
      with:
        namcapExcludeRules: unusedsodepends

    - name: Upload Package Archive
      uses: actions/upload-artifact@v3.1.0
      with:
        name: easyeffects-archlinux-${{ needs.prepare.outputs.github_commit_desc }}-x86_64
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
        if-no-files-found: error
