on:
  push:
    branches: [ master ]
  pull_request:
name: CI
jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: easyeffects.flatpak
        manifest-path: util/flatpak/com.github.wwmm.easyeffects.json
        cache-key: flatpak-builder-${{ github.sha }}   
  arch:
    name: Arch
    runs-on: ubuntu-20.04
    container:
      image: archlinux
    
    steps:
    - name: prepare
      run: |
        pacman -Syu --noconfirm git
        useradd build -m
        cd /home/build
       # su build
              
    - name: build
      run: |
        ls
        pwd
        git clone https://github.com/wwmm/easyeffects
        cd easyeffects
        ls
        cat PKGBUILD
        # becuase makepkg complains when being run as root, workaround with https://bbs.archlinux.org/viewtopic.php?pid=1729990#p1729990
        source PKGBUILD && pacman -Syu --noconfirm --needed --asdeps "${makedepends[@]}" "${depends[@]}"
        su build
        makepkg -si

      
      
