name: Get commit description

on:
  workflow_call:
    inputs:
      is_pr:
        required: true
        type: boolean
    outputs:
      github_commit_desc:
        description: "The commit description"
        value: ${{ jobs.commit_description.outputs.github_commit_desc }}

jobs:
  commit_description:
    name: Get commit description
    runs-on: ubuntu-20.04
    outputs:
      github_commit_desc: ${{ steps.get_commit_desc.outputs.github_commit_desc }}
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Get head branch latest commit
        run: echo "GITHUB_HEAD_SHA=$(git log --pretty=format:'%h' $GITHUB_SHA^2 -1)" >> $GITHUB_ENV
      - name: Get base branch latest commit
        run: echo "GITHUB_BASE_SHA=base_sha_pretend" >> $GITHUB_ENV
      - name: Get latest commit
        run: echo "GITHUB_HEAD_SHA=$(git log --pretty=format:'%h' -1)" >> $GITHUB_ENV
      - id: get_commit_desc
        run: | 
          if [[ ${{ inputs.is_pr }} == 'true' ]]; then
            echo "::set-output name=github_commit_desc::merge-${{ GITHUB_HEAD_SHA }}-into-${{ GITHUB_BASE_SHA }}"
          else
            echo "::set-output name=github_commit_desc::master-${{ GITHUB_HEAD_SHA }}"
          fi