name: Flatpak dependency updates
on:
  schedule: # for scheduling to work this file must be in the default branch
  - cron: "0 0 * * *" # run every day
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 

jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3.0.2
    
    - name: Run flatpak-external-data-checker
      run: |
        GIT_USER_NAME=$(git config user.name)
        GIT_USER_EMAIL=$(git config user.email)

        CWD=$(pwd)

        docker run --rm --privileged \
          -v $HOME:$HOME:rslave \
          -v $CWD:$CWD:rslave \
          -w $CWD \
          -e GIT_AUTHOR_NAME="EasyEffects Bot" \
          -e GIT_COMMITTER_NAME="EasyEffects Bot" \
          -e GIT_AUTHOR_EMAIL="110548574+easyeffects-bot@users.noreply.github.com" \
          -e GIT_COMMITTER_EMAIL="110548574+easyeffects-bot@users.noreply.github.com" \
          -e EMAIL="110548574+easyeffects-bot@users.noreply.github.com" \
          -e GITHUB_TOKEN="${{ secrets.EASYEFFECTS_BOT }}"  \
          -it ghcr.io/latest/flatpak-external-data-checker:latest \
          --always-fork --update util/flatpak/com.github.wwmm.easyeffects.json