name: Flatpak dependency updates
on:
  schedule: # for scheduling to work this file must be in the default branch
  - cron: "0 0 * * *" # run every day
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 

jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: EasyEffects Bot
          GIT_COMMITTER_NAME: EasyEffects Bot
          # email sets "EasyEffects Bot" user as commit author
          GIT_AUTHOR_EMAIL: 110548574+easyeffects-bot@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 110548574+easyeffects-bot@users.noreply.github.com
          EMAIL: 110548574+easyeffects-bot@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.EASYEFFECTS_BOT }}
        with:
          args: --update --always-fork util/flatpak/com.github.wwmm.easyeffects.json