name: Flatpak dependency updates
on:
  schedule: # for scheduling to work this file must be in the default branch
  - cron: "0 0 * * *" # run every day
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab 
  push:

jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0
    
    - name: Run flatpak-external-data-checker
      run: |
        CWD=$(pwd)
                
        podman run --rm --privileged \
          -v $HOME:$HOME:rslave \
          -v $CWD:$CWD:rslave \
          -w $CWD \
          -e GIT_AUTHOR_NAME="EasyEffects Bot" \
          -e GIT_COMMITTER_NAME="EasyEffects Bot" \
          -e GIT_AUTHOR_EMAIL="110548574+easyeffects-bot@users.noreply.github.com" \
          -e GIT_COMMITTER_EMAIL="110548574+easyeffects-bot@users.noreply.github.com" \
          -e EMAIL="110548574+easyeffects-bot@users.noreply.github.com" \
          -e GITHUB_TOKEN="${{ secrets.EASYEFFECTS_BOT }}" \
          ghcr.io/vchernin/flatpak-external-data-checker:test \
          --always-fork --update util/flatpak/com.github.wwmm.easyeffects.json